## discovery-deployment.yaml
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: discovery
#  namespace: inventory
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: discovery
#  template:
#    metadata:
#      labels:
#        app: discovery
#    spec:
#      containers:
#        - name: discovery
#          image: mohammed.azurecr.io/discovery
#          ports:
#            - containerPort: 8761
#          env:
#            - name: EUREKA_INSTANCE_HOSTNAME
#              value: "discovery"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8761
#            initialDelaySeconds: 90
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8761
#            initialDelaySeconds: 60
#            periodSeconds: 5
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: discovery
#  namespace: inventory
#spec:
#  selector:
#    app: discovery
#  ports:
#    - port: 8761
#      targetPort: 8761
#  type: ClusterIP
#
