# raw-material-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-material-service
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw-material-service
  template:
    metadata:
      labels:
        app: raw-material-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8092"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: raw-material-service
          image: mohammed.azurecr.io/raw-material-service
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 190
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 190
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: raw-material-service
  namespace: inventory
  labels:
    app: raw-material-service
spec:
  selector:
    app: raw-material-service
  ports:
    - name: http
      port: 8092
      targetPort: 8092
  type: ClusterIP