# raw-material-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-material-service
  namespace: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raw-material-service
  template:
    metadata:
      labels:
        app: raw-material-service
    spec:
      containers:
        - name: raw-material-service
          image: mohammed.azurecr.io/raw-material-service:latest
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 90
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: raw-material-service
  namespace: inventory
spec:
  selector:
    app: raw-material-service
  ports:
    - port: 8092
      targetPort: 8092
  type: ClusterIP

