# supplier-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8091"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: supplier-service
          image: mohammed.azurecr.io/supplier-service
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 190
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 190
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  namespace: inventory
  labels:
    app: supplier-service
spec:
  selector:
    app: supplier-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
  type: ClusterIP