name: CI/CD Raw Material Service

on:
  push:
    branches:
      - main
    paths:
      - 'raw-material/**'
      - '.github/workflows/raw-material-service.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -f raw-material/pom.xml clean package -DskipTests

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name mohammed

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=mohammed.azurecr.io/raw-material-service
          docker build -t $IMAGE_NAME:${{ github.sha }} ./raw-material
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: aks
          resource-group: aks-Cloud

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/raw-material-deployment raw-material=mohammed.azurecr.io/raw-material-service:${{ github.sha }} -n inventory
          kubectl rollout status deployment/raw-material-deployment -n inventory
